const CountriesActionTypes = {
    FETCH_COUNTRIES_DATA_START: 'FETCH_COUNTRIES_DATA_START',
    FETCH_COUNTRIES_DATA_SUCCESS: 'FETCH_COUNTRIES_DATA_SUCCESS',
    FETCH_COUNTRIES_DATA_FAILURE: 'FETCH_COUNTRIES_DATA_FAILURE',
};

export default CountriesActionTypes;
