const DailyActionTypes = {
    FETCH_DAILY_DATA_START: 'FETCH_DAILY_DATA_START',
    FETCH_DAILY_DATA_SUCCESS: 'FETCH_DAILY_DATA_SUCCESS',
    FETCH_DAILY_DATA_FAILURE: 'FETCH_DAILY_DATA_FAILURE',
};

export default DailyActionTypes;
