const GlobalActionTypes = {
    FETCH_GLOBAL_DATA_START: 'FETCH_GLOBAL_DATA_START',
    FETCH_GLOBAL_DATA_SUCCESS: 'FETCH_GLOBAL_DATA_SUCCESS',
    FETCH_GLOBAL_DATA_FAILURE: 'FETCH_GLOBAL_DATA_FAILURE',
};

export default GlobalActionTypes;
